### ISSUE TITLE
Quite big memory footprint. Is this normal?

### ISSUE THREAD

**Issue by loxs** [mochi/egeoip#13]
I just started using egeoip and the reserved memory of the erlang VM went up from ~60MB to ~270MB
on 64 bit erlang 17.3

Not that it's a huge problem, just asking if it's normal.

**Comment by etrepum** [comment]
That doesn't sound bad. The database is read into memory. It would be a problem if it kept growing but the cost to use it should be relatively constant past that.

**Comment by loxs** [comment]
thanks for the clarification
