### ISSUE TITLE
How to merge MaxMinds "GeoIPOrg", "GeoIPISP" and "GeoIPCity" into egeoip

### ISSUE THREAD

**Issue by barakath** [mochi/egeoip#4]
Hi,

Can any one help me out to How to merge MaxMinds "GeoIPOrg", "GeoIPISP" and "GeoIPCity" into egeoip.

I am planning to get the "GeoIPCity" along with "GeoIPOrg" and "GeoIPISP".

Thanks

**Comment by etrepum** [comment]
Only GeoIP City / Country is supported. We don't have plans to add org or isp support, or create a method for merging the databases. You can try using egeoip with the org or ISP databases, it might even work, but you'd have to change some code to make it possible to have all three loaded at the same time, or to have multiple egeoip applications running at the same time.
